name: Chess Games & Stats Action

on:
  schedule:
    - cron: "30 1 1 * *" # Runs at 01:30 UTC in the first day of the mounth

  workflow_dispatch:

jobs:
  update-readme:
    name: Update readme with your chess stats and games
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: Balastrong/chess-stats-action@main
        with:
          CHESS_USERNAME: luisbernardinello
          GAMES_SIZE: 3
